#!/usr/bin/env bash

# see https://askubuntu.com/questions/1297805/toggle-background-opacity-option-in-alacritty

## If alacritty.toml does not exist, raise an alert
[[ ! -f ~/.config/alacritty/alacritty.toml ]] && \
    notify-send "alacritty.toml does not exist" && exit 0

# ## Fetch background_opacity from alacritty.toml
# opacity=$(awk '$1 == "opacity=" {print $2; exit}' ~/.config/alacritty/alacritty.toml)
# ## updated command with field separator, works
opacity=$(awk -F= '/^opacity=/ {print $2; exit}' ~/.config/alacritty/alacritty.toml)

## Assign toggle opacity value
case $opacity in
  1)
    toggle_opacity=0.8
    ;;
  *)
    toggle_opacity=1
    ;;
esac

## Replace opacity value in alacritty.toml
sed -i -- "s/opacity=$opacity/opacity=$toggle_opacity/" \
    ~/.config/alacritty/alacritty.toml

# make executable afterwarks
# chmod +x
